<?php

/*
 * (c) Our Code World <dev@ourcodeworld.com>
 *
 * This library is a PHP port (written by Our Code World) of the JavaScript library NTC JS.
 *
    +-----------------------------------------------------------------+
    |     Created by Chirag Mehta - http://chir.ag/projects/ntc       |
    |-----------------------------------------------------------------|
    |               ntc js (Name that Color JavaScript)               |
    +-----------------------------------------------------------------+

    All the functions, code, lists etc. have been written specifically
    for the Name that Color JavaScript by Chirag Mehta unless otherwise
    specified.

    http://chir.ag/projects/ntc/
 * 
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace ourcodeworld\NameThatColor;

class ColorInterpreter {

    public function __construct(){
        $color = null;
        $rgb = null;
        $hsl = null;

        for($i = 0; $i < count($this->names); $i++)
        {
            $color = "#" . $this->names[$i][0];
            $rgb = $this->rgb($color);
            $hsl = $this->hsl($color);

            array_push(
                $this->names[$i], 
                $rgb[0], 
                $rgb[1], 
                $rgb[2], 
                $hsl[0], 
                $hsl[1], 
                $hsl[2]
            );
        }   
    }

    public function name($color){
        $color = strtoupper($color);

        if(strlen($color) < 3 || strlen($color) > 7){
            return array(
                "hex" => "#000000",
                "name" => "Invalid Color: " . $color,
                "exact" => false
            );
        }
        
        // If given the format without #
        if(strlen($color) % 3 == 0){
            $color = "#" . $color;
        }
        
        // If given #fea, duplicate every char e.g #ffeeaa
        if(strlen($color) == 4){
            $color = "#" . $color.substr(1, 1) . $color.substr(1, 1) . $color.substr(2, 1) . $color.substr(2, 1) . $color.substr(3, 1) . $color.substr(3, 1);
        }
          
        $rgb = $this->rgb($color);

        $r = $rgb[0];
        $g = $rgb[1];
        $b = $rgb[2];

        $hsl = $this->hsl($color);

        $h = $hsl[0];
        $s = $hsl[1];
        $l = $hsl[2];

        $ndf1 = 0; 
        $ndf2 = 0; 
        $ndf = 0;

        $cl = -1;
        $df = -1;
    
        for($i = 0; $i < count($this->names); $i++)
        {
            if($color == "#" . $this->names[$i][0]){
                return array(
                    "hex" => "#" . $this->names[$i][0], 
                    "name" => $this->names[$i][1], 
                    "exact" => true
                );
            }

            $ndf1 = pow($r - $this->names[$i][2], 2) + pow($g - $this->names[$i][3], 2) + pow($b - $this->names[$i][4], 2);
            $ndf2 = pow($h - $this->names[$i][5], 2) + pow($s - $this->names[$i][6], 2) + pow($l - $this->names[$i][7], 2);
            $ndf = $ndf1 + $ndf2 * 2;

            if($df < 0 || $df > $ndf)
            {
                $df = $ndf;
                $cl = $i;
            }
        }
        
        if($cl < 0){
            return array(
                "hex" => "#000000",
                "name" => "Invalid Color: " . $color,
                "exact" => false
            );
        }else{
            return array(
                "hex" => "#" . $this->names[$cl][0],
                "name" => $this->names[$cl][1],
                "exact" => false
            );
        }
    }

    // adopted from: Farbtastic 1.2
    // http://acko.net/dev/farbtastic
    public function hsl($color) {
        $rgb = array(
            intval(hexdec(substr($color, 1, 2))) / 255, 
            intval(hexdec(substr($color, 3, 2))) / 255, 
            intval(hexdec(substr($color, 5, 7))) / 255
        );

        $min = null;
        $max = null;
        $delta = null;
        $h = null;
        $s = null;
        $l = null;

        $r = $rgb[0];
        $g = $rgb[1];
        $b = $rgb[2];

        $min = min($r, min($g, $b));
        $max = max($r, max($g, $b));
        $delta = $max - $min;
        $l = ($min + $max) / 2;

        $s = 0;
        if($l > 0 && $l < 1)
        $s = $delta / ($l < 0.5 ? (2 * $l) : (2 - 2 * $l));

        $h = 0;
        if($delta > 0)
        {
            if ($max == $r && $max != $g) $h += ($g - $b) / $delta;
            if ($max == $g && $max != $b) $h += (2 + ($b - $r) / $delta);
            if ($max == $b && $max != $r) $h += (4 + ($r - $g) / $delta);
            $h /= 6;
        }

        return array(
            intval($h * 255), 
            intval($s * 255),
            intval($l * 255)
        );
    }

    // adopted from: Farbtastic 1.2
    // http://acko.net/dev/farbtastic
    public function rgb($color) {
        return array(
            hexdec(substr($color, 1, 2)), 
            hexdec(substr($color, 3, 2)),  
            hexdec(substr($color, 5, 7))
        );
    }

    public $names = array(
        array("000000", "Preto"),
        array("000080", "Azul-marinho"),
        array("0000C8", "Azul escuro"),
        array("0000FF", "Azul"),
        array("000741", "Stratos"),
        array("001B1C", "Pântano"),
        array("002387", "Resolução Azul"),
        array("002900", "Abeto profundo"),
        array("002E20", "Burnham"),
        array("002FA7", "Internacional Klein Blue"),
        array("003153", "Azul da Prússia"),
        array("003366", "Azul da meia noite"),
        array("003399", "Smalt"),
        array("003532", "Cerceta Profunda"),
        array("003E40", "Chipre"),
        array("004620", "Kaitoke Verde"),
        array("0047AB", "Cobalto"),
        array("004816", "Crusoé"),
        array("004950", "Sherpa Blue"),
        array("0056A7", "Empreendimento"),
        array("00581A", "Camarone"),
        array("0066CC", "Ciência Azul"),
        array("0066FF", "Fita Azul"),
        array("00755E", "Floresta tropical"),
        array("0076A3", "Todos os portos"),
        array("007BA7", "Cerúleo Profundo"),
        array("007EC7", "Lochmara"),
        array("007FFF", "Resplendor do Azure"),
        array("008080", "Cerceta"),
        array("0095B6", "Bondi Blue"),
        array("009DC4", "Azul Pacífico"),
        array("00A693", "Verde persa"),
        array("00A86B", "Jade"),
        array("00CC99", "Verde Caribe"),
        array("00CCCC", "Ovo Azul de Robin"),
        array("00FF00", "Verde"),
        array("00FF7F", "Primavera verde"),
        array("00FFFF", "Ciano / Aqua"),
        array("010D1A", "Carvão Azul"),
        array("011635", "Meia-noite"),
        array("011D13", "Azevinho"),
        array("012731", "Daintree"),
        array("01361C", "Cardin Green"),
        array("01371A", "Condado Verde"),
        array("013E62", "Astronauta Azul"),
        array("013F6A", "Azul Real"),
        array("014B43", "Água Profunda"),
        array("015E85", "Orientar"),
        array("016162", "Pedra Azul"),
        array("016D39", "Verde divertido"),
        array("01796F", "Verde Pinho"),
        array("017987", "Lagoa Azul"),
        array("01826B", "Mar profundo"),
        array("01A368", "Névoa Verde"),
        array("022D15", "azevinho inglês"),
        array("02402C", "Sherwood Green"),
        array("02478E", "Congresso Azul"),
        array("024E46", "Noite do mar"),
        array("026395", "Azul Bahama"),
        array("02866F", "Observatório"),
        array("02A4D3", "cerúleo"),
        array("03163C", "Tangaroa"),
        array("032B52", "Vogue Verde"),
        array("036A6E", "Mesquita"),
        array("041004", "Musgo da meia-noite"),
        array("041322", "Pérola Negra"),
        array("042E4C", "Baleia Azul"),
        array("044022", "Abobrinha"),
        array("044259", "Verde-azulado"),
        array("051040", "Enseada Profunda"),
        array("051657", "Golfo Azul"),
        array("055989", "Veneza Azul"),
        array("056F57", "Curso de água"),
        array("062A78", "Catalina Azul"),
        array("063537", "Tibre"),
        array("069B81", "Gossamer"),
        array("06A189", "Niágara"),
        array("073A50", "Tarawera"),
        array("080110", "Jaguar"),
        array("081910", "Feijão preto"),
        array("082567", "Safira Profunda"),
        array("088370", "Elfo Verde"),
        array("08E8DE", "Turquesa brilhante"),
        array("092256", "Rio abaixo"),
        array("09230F", "Palm Green"),
        array("09255D", "Madison"),
        array("093624", "Garrafa verde"),
        array("095859", "Verde Mar Profundo"),
        array("097F4B", "Salem"),
        array("0A001C", "russo negro"),
        array("0A480D", "Samambaia Negra"),
        array("0A6906", "louro japonês"),
        array("0A6F75", "Atol"),
        array("0B0B0B", "Bacalhau Cinzento"),
        array("0B0F08", "Pântano"),
        array("0B1107", "Gordons Green"),
        array("0B1304", "Floresta Negra"),
        array("0B6207", "São Félix"),
        array("0BDA51", "Malaquita"),
        array("0C0B1D", "Ébano"),
        array("0C0D0F", "Fumaça de madeira"),
        array("0C1911", "Corrida Verde"),
        array("0C7A79", "Verde Surfista"),
        array("0C8990", "Arrepio Azul"),
        array("0D0332", "Rocha Negra"),
        array("0D1117", "Bunker"),
        array("0D1C19", "asteca"),
        array("0D2E1C", "Arbusto"),
        array("0E0E18", "Cinza"),
        array("0E2A30", "Vagalume"),
        array("0F2D9E", "Baía de Torea"),
        array("10121D", "Vulcano"),
        array("101405", "Green Waterloo"),
        array("105852", "Éden"),
        array("110C6C", "Arapawa"),
        array("120A8F", "Ultramarino"),
        array("123447", "Elefante"),
        array("126B40", "Jóia"),
        array("130000", "Diesel"),
        array("130A06", "Asfalto"),
        array("13264D", "Zodíaco Azul"),
        array("134F19", "Salsinha"),
        array("140600", "Nero"),
        array("1450AA", "Azul Tory"),
        array("151F4C", "Estamenha"),
        array("1560BD", "Jeans"),
        array("15736B", "Génova"),
        array("161928", "Miragem"),
        array("161D10", "Verde caçador"),
        array("162A40", "Grande pedra"),
        array("163222", "céltico"),
        array("16322C", "Verde Madeira"),
        array("163531", "Empena Verde"),
        array("171F04", "Pinheiro"),
        array("175579", "Chathams Blue"),
        array("182D09", "Verde Floresta Profunda"),
        array("18587A", "Blumine"),
        array("19330E", "Folha de palmeira"),
        array("193751", "Azul Nilo"),
        array("1959A8", "Azul divertido"),
        array("1A1A68", "Ponto da Sorte"),
        array("1AB385", "Prado da Montanha"),
        array("1B0245", "Tolopea"),
        array("1B1035", "Haiti"),
        array("1B127B", "Koamaru Profundo"),
        array("1B1404", "Acádia"),
        array("1B2F11", "Algas marinhas"),
        array("1B3162", "Biscaia"),
        array("1B659D", "Matisse"),
        array("1C1208", "Cabeça de Corvo"),
        array("1C1E13", "Verde Rangum"),
        array("1C39BB", "Azul persa"),
        array("1C402E", "Everglade"),
        array("1C7C7D", "Olmo"),
        array("1D6142", "Ervilha verde"),
        array("1E0F04", "crioulo"),
        array("1E1609", "Karaka"),
        array("1E1708", "El Paso"),
        array("1E385B", "Violoncelo"),
        array("1E433C", "Te Papa Green"),
        array("1E90FF", "Trapaceiro azul"),
        array("1E9AB0", "Azul Oriental"),
        array("1F120F", "Cavaleiro Noturno"),
        array("1FC2C2", "Java"),
        array("20208D", "Jacksons Roxo"),
        array("202E54", "Explosão de Nuvem"),
        array("204852", "Dianne Azul"),
        array("211A0E", "Eternidade"),
        array("220878", "Azul profundo"),
        array("228B22", "Verde floresta"),
        array("233418", "Pato-real"),
        array("240A40", "Tolet"),
        array("240C02", "Kilamanjaro"),
        array("242A1D", "Cabana de Madeira"),
        array("242E16", "Azeitona preta"),
        array("24500F", "Estufa"),
        array("251607", "Grafite"),
        array("251706", "Canhão Negro"),
        array("251F4F", "Porto Gore"),
        array("25272C", "Tubarão"),
        array("25311C", "Alga Verde"),
        array("2596D1", "Azul curioso"),
        array("260368", "Pauá"),
        array("26056A", "Paris M"),
        array("261105", "Casca de Madeira"),
        array("261414", "Gôndola"),
        array("262335", "Aço cinza"),
        array("26283B", "Argila de Ébano"),
        array("273A81", "Baía de Muitos"),
        array("27504B", "Plantação"),
        array("278A5B", "Eucalipto"),
        array("281E15", "Óleo"),
        array("283A77", "Astronauta"),
        array("286ACD", "Marinheiro"),
        array("290C5E", "Violeta Violenta"),
        array("292130", "Bastilha"),
        array("292319", "Zeus"),
        array("292937", "Charada"),
        array("297B9A", "Jujuba"),
        array("29AB87", "Verde Selva"),
        array("2A0359", "Torta de cereja"),
        array("2A140E", "Grão de café"),
        array("2A2630", "Mar Báltico"),
        array("2A380B", "Tartaruga Verde"),
        array("2A52BE", "Azul cerúleo"),
        array("2B0202", "Preto Sépia"),
        array("2B194F", "Valhalla"),
        array("2B3228", "Metal pesado"),
        array("2C0E8C", "Gema Azul"),
        array("2C1632", "Revólver"),
        array("2C2133", "Cedro Branqueado"),
        array("2C8C84", "Lochinvar"),
        array("2D2510", "Mikado"),
        array("2D383A", "Espaço sideral"),
        array("2D569B", "St Tropaz"),
        array("2E0329", "Jacarandá"),
        array("2E1905", "Jacko Bean"),
        array("2E3222", "Rangitoto"),
        array("2E3F62", "Rinoceronte"),
        array("2E8B57", "Verde Mar"),
        array("2EBFD4", "Lambreta"),
        array("2F270E", "Cebola"),
        array("2F3CB3", "Baía do Governador"),
        array("2F519E", "Safira"),
        array("2F5A57", "Espectro"),
        array("2F6168", "Casal"),
        array("300529", "Melanzane"),
        array("301F1E", "Cacau Marrom"),
        array("302A0F", "Woodrush"),
        array("304B6A", "San Juan"),
        array("30D5C8", "Turquesa"),
        array("311C17", "Eclipse"),
        array("314459", "Bluewood em conserva"),
        array("315BA1", "Azure"),
        array("31728D", "Calipso"),
        array("317D82", "Paraíso"),
        array("32127A", "índigo persa"),
        array("32293A", "groselha negra"),
        array("323232", "Eixo da Mina"),
        array("325D52", "Stromboli"),
        array("327C14", "Bilbau"),
        array("327DA0", "Astral"),
        array("33036B", "Christalle"),
        array("33292F", "Trovão"),
        array("33CC99", "Trevo"),
        array("341515", "Tamarindo"),
        array("350036", "Carnaval"),
        array("350E42", "Valentino"),
        array("350E57", "Jagger"),
        array("353542", "Atum"),
        array("354E8C", "Chambray"),
        array("363050", "Martinica"),
        array("363534", "Tuatara"),
        array("363C0D", "Waiouru"),
        array("36747D", "Ming"),
        array("368716", "Palma"),
        array("370202", "Chocolate"),
        array("371D09", "Clínquer"),
        array("37290E", "Tumbleweed marrom"),
        array("373021", "bétula"),
        array("377475", "Oráculo"),
        array("380474", "Diamante azul"),
        array("381A51", "Uva"),
        array("383533", "Duna"),
        array("384555", "Oxford Azul"),
        array("384910", "Trevo"),
        array("394851", "Abeto calcário"),
        array("396413", "Dell"),
        array("3A0020", "Toledo"),
        array("3A2010", "Sambuca"),
        array("3A2A6A", "Jacarta"),
        array("3A686C", "William"),
        array("3A6A47", "Killarney"),
        array("3AB09E", "Keppel"),
        array("3B000B", "tentadora"),
        array("3B0910", "Beringela"),
        array("3B1F1F", "Jon"),
        array("3B2820", "casa na árvore"),
        array("3B7A57", "Amazonas"),
        array("3B91B4", "Boston Blue"),
        array("3C0878", "Windsor"),
        array("3C1206", "Rebelde"),
        array("3C1F76", "Meteorito"),
        array("3C2005", "Ébano escuro"),
        array("3C3910", "Camuflar"),
        array("3C4151", "Cinza brilhante"),
        array("3C4443", "Bacalhau do Cabo"),
        array("3C493A", "Verde Lunar"),
        array("3D0C02", "Feijão"),
        array("3D2B1F", "Bistre"),
        array("3D7D52", "Goblin"),
        array("3E0480", "Margarida Martim-pescador"),
        array("3E1C14", "Cedro"),
        array("3E2B23", "noz inglesa"),
        array("3E2C1C", "Espadim Negro"),
        array("3E3A44", "Navio Cinza"),
        array("3EABBF", "Peloroso"),
        array("3F2109", "Bronze"),
        array("3F2500", "Cola"),
        array("3F3002", "Madras"),
        array("3F307F", "Minsk"),
        array("3F4C3A", "Ponto de repolho"),
        array("3F583B", "Polegar Tom"),
        array("3F5D53", "Verde Mineral"),
        array("3FC1AA", "Porto Rico"),
        array("3FFF00", "Arlequim"),
        array("401801", "Cápsula marrom"),
        array("40291D", "Cortiça"),
        array("403B38", "Masala"),
        array("403D19", "Palha Verde"),
        array("405169", "Fiorde"),
        array("40826D", "Viridiano"),
        array("40A860", "Castelo Verde"),
        array("410056", "Ameixa madura"),
        array("411F10", "Paco"),
        array("412010", "Carvalho Profundo"),
        array("413C37", "Merlim"),
        array("414257", "Pólvora"),
        array("414C7D", "Baía do leste"),
        array("4169E1", "Azul Real"),
        array("41AA78", "Oceano Verde"),
        array("420303", "marrom queimado"),
        array("423921", "Lisboa Marrom"),
        array("427977", "Jade desbotado"),
        array("431560", "Goma Escarlate"),
        array("433120", "Iroko"),
        array("433E37", "Tatu"),
        array("434C59", "Leito do rio"),
        array("436A0D", "Folha verde"),
        array("44012D", "Barossa"),
        array("441D00", "Marrocos Marrom"),
        array("444954", "Mako"),
        array("454936", "Kelp"),
        array("456CAC", "São Marinho"),
        array("45B1E8", "Azul Picton"),
        array("460B41", "Loulou"),
        array("462425", "Cratera Marrom"),
        array("465945", "Espargos Cinzentos"),
        array("4682B4", "Azul Aço"),
        array("480404", "Vermelho Rústico"),
        array("480607", "Rosa búlgara"),
        array("480656", "Clarividente"),
        array("481C1C", "Semente de cacau"),
        array("483131", "Marrom amadeirado"),
        array("483C32", "Taupe"),
        array("49170C", "Van Cleef"),
        array("492615", "Brown Derby"),
        array("49371B", "Bronze Metálico"),
        array("495400", "Verde Verdun"),
        array("496679", "Blue Bayoux"),
        array("497183", "Bismark"),
        array("4A2A04", "Samambaia"),
        array("4A3004", "Bronze Profundo"),
        array("4A3C30", "Mondo"),
        array("4A4244", "Tundora"),
        array("4A444B", "Cascalho"),
        array("4A4E5A", "Truta"),
        array("4B0082", "Pigmento índigo"),
        array("4B5D52", "Nandor"),
        array("4C3024", "Selim"),
        array("4C4F56", "Mosteiro"),
        array("4D0135", "Amora"),
        array("4D0A18", "Economia de táxi"),
        array("4D1E01", "bronzeado indiano"),
        array("4D282D", "Vaqueiro"),
        array("4D282E", "Marrom lívido"),
        array("4D3833", "Pedra"),
        array("4D3D14", "Punga"),
        array("4D400F", "Bronzetone"),
        array("4D5328", "Floresta"),
        array("4E0606", "Mogno"),
        array("4E2A5A", "Bossa nova"),
        array("4E3B41", "Matterhorn"),
        array("4E420C", "Azeitona Bronze"),
        array("4E4562", "Vinho com canela"),
        array("4E6649", "Axolote"),
        array("4E7F9E", "Wedgewood"),
        array("4EABD1", "Shakespeare"),
        array("4F1C70", "Flor de mel"),
        array("4F2398", "Margarida Bush"),
        array("4F69C6", "Índigo"),
        array("4F7942", "Samambaia Verde"),
        array("4F9D5D", "Salada de frutas"),
        array("4FA83D", "Maçã"),
        array("504351", "Argamassa"),
        array("507096", "Azul da Caxemira"),
        array("507672", "Cutty Sark"),
        array("50C878", "Esmeralda"),
        array("514649", "Imperador"),
        array("516E3D", "Chalé Verde"),
        array("517C66", "Como"),
        array("51808F", "Azul Esmaltado"),
        array("52001F", "Castro"),
        array("520C17", "Carvalho Marrom"),
        array("523C94", "Giga"),
        array("533455", "Vodu"),
        array("534491", "Vitória"),
        array("53824B", "Verde hippie"),
        array("541012", "Charneca"),
        array("544333", "Juiz Gray"),
        array("54534D", "Cinza Fusco"),
        array("549019", "Vida Loca"),
        array("55280C", "Cioccolato"),
        array("555B10", "Saratoga"),
        array("556D56", "Finlândia"),
        array("5590D9", "Havelock azul"),
        array("56B4BE", "Fonte Azul"),
        array("578363", "Folhas de Primavera"),
        array("583401", "Sela Marrom"),
        array("585562", "Scarpa Flow"),
        array("587156", "Cacto"),
        array("589AAF", "Azul Hippie"),
        array("591D35", "Baga de Vinho"),
        array("592804", "Amora castanha"),
        array("593737", "Castanho do Congo"),
        array("594433", "Millbrook"),
        array("5A6E9C", "Waikawa Gray"),
        array("5A87A0", "Horizonte"),
        array("5B3013", "Jambalaya"),
        array("5C0120", "Bordéus"),
        array("5C0536", "Madeira de Amoreira"),
        array("5C2E01", "Carnaby Tan"),
        array("5C5D75", "Cometa"),
        array("5D1E0F", "Redwood"),
        array("5D4C51", "Dom Juan"),
        array("5D5C58", "Chicago"),
        array("5D5E37", "Verdete"),
        array("5D7747", "Dingley"),
        array("5DA19F", "Baía do disjuntor"),
        array("5E483E", "Cabul"),
        array("5E5D3B", "Cicuta"),
        array("5F3D26", "Café irlandês"),
        array("5F5F6E", "Cinza médio"),
        array("5F6672", "Transporte Cinza"),
        array("5FA777", "Floresta Aquática"),
        array("5FB3AC", "Vento de comércio"),
        array("604913", "Pescoço de Cavalo"),
        array("605B73", "Esfumaçado"),
        array("606E68", "Veludo"),
        array("6093D1", "Danúbio"),
        array("612718", "Expresso"),
        array("614051", "Beringela"),
        array("615D30", "Costa do Sol"),
        array("61845F", "Clareira Verde"),
        array("622F30", "Corsário"),
        array("623F2D", "Quincy"),
        array("624E9A", "Arbusto de Borboleta"),
        array("625119", "Costa oeste"),
        array("626649", "passarinho"),
        array("639A8F", "Pátina"),
        array("63B76C", "Samambaia"),
        array("6456B7", "Azul Violeta"),
        array("646077", "Golfinho"),
        array("646463", "Pó de Tempestade"),
        array("646A54", "Sião"),
        array("646E75", "Nevada"),
        array("6495ED", "Azul Centáurea"),
        array("64CCDB", "Viking"),
        array("65000B", "Jacarandá"),
        array("651A14", "Madeira de cerejeira"),
        array("652DC1", "Coração roxo"),
        array("657220", "Samambaia"),
        array("65745D", "Salgueiro"),
        array("65869F", "Hoki"),
        array("660045", "Pompadour"),
        array("660099", "Roxa"),
        array("66023C", "Tyrian Purple"),
        array("661010", "Bronzeado escuro"),
        array("66B58F", "Árvore de Prata"),
        array("66FF00", "Verde claro"),
        array("66FF66", "Verde gritando"),
        array("67032D", "Rosa preta"),
        array("675FA6", "Scampi"),
        array("676662", "Cinza Ironside"),
        array("678975", "Verde Viridiano"),
        array("67A712", "Christi"),
        array("683600", "Acabamento em madeira de noz-moscada"),
        array("685558", "Zambeze"),
        array("685E6E", "Caixa de sal"),
        array("692545", "Porto Tawny"),
        array("692D54", "finlandês"),
        array("695F62", "Escorpião"),
        array("697E9A", "Lynch"),
        array("6A442E", "especiaria"),
        array("6A5D1B", "Himalaia"),
        array("6A6051", "Soja"),
        array("6B2A14", "Charneca Peluda"),
        array("6B3FA0", "Roxo Real"),
        array("6B4E31", "Shingle Fawn"),
        array("6B5755", "Dourado"),
        array("6B8BA2", "Bermudas Cinza"),
        array("6B8E23", "Azeitona"),
        array("6C3082", "Eminência"),
        array("6CDAE7", "Azul turquesa"),
        array("6D0101", "Estrela Solitária"),
        array("6D5E54", "Pinha"),
        array("6D6C6C", "Pomba Cinza"),
        array("6D9292", "Zimbro"),
        array("6D92A1", "gótico"),
        array("6E0902", "Óxido Vermelho"),
        array("6E1D14", "Moccacino"),
        array("6E4826", "Feijão em Conserva"),
        array("6E4B26", "Dallas"),
        array("6E6D57", "Kokoda"),
        array("6E7783", "Céu pálido"),
        array("6F440C", "Café Royale"),
        array("6F6A61", "pedra"),
        array("6F8E63", "Terras Altas"),
        array("6F9D02", "Limonada de lima"),
        array("6FD0C5", "felpudo"),
        array("701C1C", "ameixa persa"),
        array("704214", "Sépia"),
        array("704A07", "Bronze antigo"),
        array("704F50", "Ferra"),
        array("706555", "Café"),
        array("708090", "Ardósia cinza"),
        array("711A00", "Acabamento em madeira de cedro"),
        array("71291D", "Cobre Metálico"),
        array("714693", "Caso"),
        array("714AB2", "Estúdio"),
        array("715D47", "Marrom Tabaco"),
        array("716338", "Metal amarelo"),
        array("716B56", "Turfa"),
        array("716E10", "Olivetone"),
        array("717486", "Cinza Tempestade"),
        array("718080", "Siroco"),
        array("71D9E2", "Azul água-marinha"),
        array("72010F", "Vermelho Veneziano"),
        array("724A2F", "Cobre Velho"),
        array("726D4E", "Vai Ben"),
        array("727B89", "Raven"),
        array("731E8F", "Sessão"),
        array("734A12", "Umber Bruto"),
        array("736C9F", "Kimberly"),
        array("736D58", "Crocodilo"),
        array("737829", "Creta"),
        array("738678", "Xanadu"),
        array("74640D", "Mostarda Picante"),
        array("747D63", "Cinzas calcárias"),
        array("747D83", "Pedra rolando"),
        array("748881", "Fumaça Azul"),
        array("749378", "Louro"),
        array("74C365", "louva a Deus"),
        array("755A57", "Russett"),
        array("7563A8", "Dilúvio"),
        array("76395D", "Cósmico"),
        array("7666C6", "Margarida Azul"),
        array("76BD17", "Lima"),
        array("76D7EA", "Céu azul"),
        array("770F05", "Borgonha escuro"),
        array("771F1F", "Coroa de Espinhos"),
        array("773F1A", "Noz"),
        array("776F61", "Paulo"),
        array("778120", "Pacifika"),
        array("779E86", "Oxley"),
        array("77DD77", "Verde pastel"),
        array("780109", "bordo japonês"),
        array("782D19", "Mocha"),
        array("782F16", "Amendoim"),
        array("78866B", "Camuflagem Verde"),
        array("788A25", "Wasabi"),
        array("788BBA", "Enseada do Navio"),
        array("78A39C", "Ninfa do Mar"),
        array("795D4C", "Café Romano"),
        array("796878", "Lavanda Velha"),
        array("796989", "Rum"),
        array("796A78", "Fedora"),
        array("796D62", "Arenito"),
        array("79DEEC", "Pulverizar"),
        array("7A013A", "Sirene"),
        array("7A58C1", "Azul fúcsia"),
        array("7A7A7A", "Pedregulho"),
        array("7A89B8", "Wild Blue Yonder"),
        array("7AC488", "De York"),
        array("7B3801", "Faia Vermelha"),
        array("7B3F00", "Canela"),
        array("7B6608", "Ouro Yukon"),
        array("7B7874", "Tapa"),
        array("7B7C94", "Waterloo"),
        array("7B8265", "Fumaça de linho"),
        array("7B9F80", "Amuleto"),
        array("7BA05B", "Espargos"),
        array("7C1C05", "cobre queniano"),
        array("7C7631", "pesto"),
        array("7C778A", "Topázio"),
        array("7C7B7A", "Concórdia"),
        array("7C7B82", "Jumbo"),
        array("7C881A", "Verde na moda"),
        array("7CA1A6", "quiabo"),
        array("7CB0A1", "Acapulco"),
        array("7CB7BB", "Netuno"),
        array("7D2C14", "Pueblo"),
        array("7DA98D", "folha de louro"),
        array("7DC8F7", "Malibu"),
        array("7DD8C6", "Bermudas"),
        array("7E3A15", "Cobre Canyon"),
        array("7F1734", "Claret"),
        array("7F3A02", "Peru bronzeado"),
        array("7F626D", "Falcão"),
        array("7F7589", "mafioso"),
        array("7F76D3", "Azul temperamental"),
        array("7FFF00", "Chartreuse"),
        array("7FFFD4", "água-marinha"),
        array("800000", "marrom"),
        array("800B47", "Cereja em botão de rosa"),
        array("801818", "Falu Red"),
        array("80341F", "Robin Vermelho"),
        array("803790", "Violeta Vívida"),
        array("80461B", "Avermelhado"),
        array("807E79", "Frei Cinza"),
        array("808000", "Oliva"),
        array("808080", "Cinza"),
        array("80B3AE", "Corrente do Golfo"),
        array("80B3C4", "Geleira"),
        array("80CCEA", "Gaivota"),
        array("81422C", "noz-moscada"),
        array("816E71", "Rosa picante"),
        array("817377", "Imperatriz"),
        array("819885", "Verde Espanhol"),
        array("826F65", "Duna de areia"),
        array("828685", "Gunsmoke"),
        array("828F72", "Encouraçado Cinza"),
        array("831923", "Merlot"),
        array("837050", "Sombra"),
        array("83AA5D", "Pepino Chelsea"),
        array("83D0C6", "Monte Carlo"),
        array("843179", "Ameixa"),
        array("84A0A0", "Vovó Smith"),
        array("8581D9", "Chetwode Blue"),
        array("858470", "Bandicoot"),
        array("859FAF", "Bali Hai"),
        array("85C4CC", "Meio Assado"),
        array("860111", "diabo Vermelho"),
        array("863C3C", "Lótus"),
        array("86483C", "Pedra de Ferro"),
        array("864D1E", "Tiro de Touro"),
        array("86560A", "Prego Enferrujado"),
        array("868974", "Amargo"),
        array("86949F", "Regente Cinza"),
        array("871550", "Discoteca"),
        array("87756E", "americano"),
        array("877C7B", "Furacão"),
        array("878D91", "Oslo Gray"),
        array("87AB39", "Sushi"),
        array("885342", "Mistura picante"),
        array("886221", "Kumera"),
        array("888387", "Suva Gray"),
        array("888D65", "Abacate"),
        array("893456", "Camelot"),
        array("893843", "Rosa sólido"),
        array("894367", "Rosa Canhão"),
        array("897D6D", "Makara"),
        array("8A3324", "Umber queimado"),
        array("8A73D6", "V verdadeiro"),
        array("8A8360", "Clay Creek"),
        array("8A8389", "Monção"),
        array("8A8F8A", "Pilha"),
        array("8AB9F1", "Jordy Blue"),
        array("8B00FF", "Violeta Elétrica"),
        array("8B0723", "Monarca"),
        array("8B6B0B", "Colheita de milho"),
        array("8B8470", "Névoa verde-oliva"),
        array("8B847E", "Escuna"),
        array("8B8680", "Cinza Natural"),
        array("8B9C90", "Manto"),
        array("8B9FEE", "Portagem"),
        array("8BA690", "Inveja"),
        array("8BA9A5", "Cascata"),
        array("8BE6D8", "correnteza"),
        array("8C055E", "Cardeal Rosa"),
        array("8C472F", "Mula Corça"),
        array("8C5738", "Argila de oleiro"),
        array("8C6495", "Rosa na moda"),
        array("8D0226", "Páprica"),
        array("8D3D38", "Castanho Sanguíneo"),
        array("8D3F3F", "Tosca"),
        array("8D7662", "Cimento"),
        array("8D8974", "Verde Granito"),
        array("8D90A1", "Peixe-boi"),
        array("8DA8CC", "Polo Azul"),
        array("8E0000", "Baga Vermelha"),
        array("8E4D1E", "Corda"),
        array("8E6F70", "Ópio"),
        array("8E775E", "Dominó"),
        array("8E8190", "Mamba"),
        array("8EABC1", "Nepal"),
        array("8F021C", "Pohutukawa"),
        array("8F3E33", "El Salva"),
        array("8F4B0E", "Korma"),
        array("8F8176", "Esquilo"),
        array("8FD6B4", "Vista Azul"),
        array("900020", "Borgonha"),
        array("901E1E", "Tijolo Velho"),
        array("907874", "Cânhamo"),
        array("907B71", "Geada de Amêndoas"),
        array("908D39", "Sicômoro"),
        array("92000A", "Sangria"),
        array("924321", "Cominho"),
        array("926F5B", "Castor"),
        array("928573", "Parede de pedra"),
        array("928590", "Vênus"),
        array("9370DB", "Roxo Médio"),
        array("93CCEA", "Centáurea"),
        array("93DFB8", "Algas Verdes"),
        array("944747", "Ferrugem de cobre"),
        array("948771", "Arrowtown"),
        array("950015", "Scarlett"),
        array("956387", "Mestre de Ataque"),
        array("959396", "Névoa da Montanha"),
        array("960018", "Carmim"),
        array("964B00", "Marrom"),
        array("967059", "Couro"),
        array("9678B6", "Majestade da Montanha Roxa"),
        array("967BB6", "Roxo Lavanda"),
        array("96A8A1", "Estanho"),
        array("96BBAB", "Verão Verde"),
        array("97605D", "Au Chico"),
        array("9771B5", "Glicínia"),
        array("97CD2D", "Atlântida"),
        array("983D61", "Vinho Vermelho"),
        array("9874D3", "Arbusto Lilás"),
        array("98777B", "Bazar"),
        array("98811B", "Fazenda"),
        array("988D77", "Ostra pálida"),
        array("98FF98", "Menta verde"),
        array("990066", "Berinjela Fresca"),
        array("991199", "Berinjela Violeta"),
        array("991613", "Tamarillo"),
        array("991B07", "Totem"),
        array("996666", "Rosa de cobre"),
        array("9966CC", "Ametista"),
        array("997A8D", "Rosa Mountbatten"),
        array("9999CC", "Sino Azul"),
        array("9A3820", "Areia da Pradaria"),
        array("9A6E61", "Torrada"),
        array("9A9577", "Gurkha"),
        array("9AB973", "Olivina"),
        array("9AC2B8", "Sombra Verde"),
        array("9B4703", "Óregon"),
        array("9B9E8F", "Capim Limão"),
        array("9C3336", "Estilete"),
        array("9D5616", "bronzeado havaiano"),
        array("9DACB7", "Gaivota Cinzenta"),
        array("9DC209", "Pistache"),
        array("9DE093", "Maçã Vovó Smith"),
        array("9DE5FF", "Anakiwa"),
        array("9E5302", "Gema de Chelsea"),
        array("9E5B40", "Pele Sépia"),
        array("9EA587", "Sábio"),
        array("9EA91F", "Cidra"),
        array("9EB1CD", "Rocha Azul"),
        array("9EDEE0", "Glória da manhã"),
        array("9F381D", "Conhaque"),
        array("9F821C", "Ouro do Recife"),
        array("9F9F9C", "Poeira estelar"),
        array("9FA0B1", "Papai Noel Cinza"),
        array("9FD7D3", "Sinbad"),
        array("9FDD8C", "Feijoa"),
        array("A02712", "Tabasco"),
        array("A1750D", "Rum amanteigado"),
        array("A1ADB5", "Acerte Cinza"),
        array("A1C50A", "Citrino"),
        array("A1DAD7", "Ilha do Aqua"),
        array("A1E9DE", "Folha de Água"),
        array("A2006D", "Flerte"),
        array("A23B6C", "Rouge"),
        array("A26645", "Cabo Palliser"),
        array("A2AAB3", "Castelo Cinzento"),
        array("A2AEAB", "Eduardo"),
        array("A3807B", "Farlap"),
        array("A397B4", "Fumaça de Ametista"),
        array("A3E3ED", "Azul Nevasca"),
        array("A4A49D", "Delta"),
        array("A4A6D3", "melancólico"),
        array("A4AF6E", "Fumaça Verde"),
        array("A50B5E", "Geléia de Jazzberry"),
        array("A59B91", "Zorba"),
        array("A5CB0C", "Bahia"),
        array("A62F20", "Telhado de terracota"),
        array("A65529", "Parl"),
        array("A68B5B", "Milho de cevada"),
        array("A69279", "Burro Marrom"),
        array("A6A29A", "Alvorecer"),
        array("A72525", "Vermelho Mexicano"),
        array("A7882C", "Ouro de Luxor"),
        array("A85307", "Ouro Rico"),
        array("A86515", "Areia do Reno"),
        array("A86B6B", "Árvore de coral"),
        array("A8989B", "Cinza empoeirado"),
        array("A899E6", "Lavanda opaca"),
        array("A8A589", "Sebo"),
        array("A8AE9C", "Broto"),
        array("A8AF8E", "Gafanhoto"),
        array("A8BD9F", "Noruega"),
        array("A8E3BD", "Chinook"),
        array("A9A491", "Azeitona Cinzenta"),
        array("A9ACB6", "Alumínio"),
        array("A9B2C3", "Azul Cadete"),
        array("A9B497", "Xisto"),
        array("A9BDBF", "Torre Cinza"),
        array("A9BEF2", "Perano"),
        array("A9C6C2", "Opala"),
        array("AA375A", "Noite Shadz"),
        array("AA4203", "Incêndio"),
        array("AA8B5B", "Muesli"),
        array("AA8D6F", "Sandália"),
        array("AAA5A9", "Senhora de pouca confiança"),
        array("AAA9CD", "Logan"),
        array("AAABB7", "Pérola fiada"),
        array("AAD6E6", "Regente St Blue"),
        array("AAF0D1", "Hortelã Mágica"),
        array("AB0563", "Batom"),
        array("AB3472", "Charneca Real"),
        array("AB917A", "Sandrift"),
        array("ABA0D9", "Púrpura Fria"),
        array("ABA196", "Bronco"),
        array("AC8A56", "Carvalho limado"),
        array("AC91CE", "zona leste"),
        array("AC9E22", "Gengibre Limão"),
        array("ACA494", "Napa"),
        array("ACA586", "Hillary"),
        array("ACA59F", "Nublado"),
        array("ACACAC", "Cálice de Prata"),
        array("ACB78E", "Pântano Verde"),
        array("ACCBB1", "Chuva de primavera"),
        array("ACDD4D", "Conífera"),
        array("ACE1AF", "Celadon"),
        array("AD781B", "Mandalay"),
        array("ADBED1", "Cásper"),
        array("ADDFAD", "Musgo verde"),
        array("ADE6C4", "Pádua"),
        array("ADFF2F", "Verde amarelo"),
        array("AE4560", "Rosa hippie"),
        array("AE6020", "Deserto"),
        array("AE809E", "Ramalhete"),
        array("AF4035", "Carmim Médio"),
        array("AF4D43", "Flor de maçã"),
        array("AF593E", "Ferrugem Marrom"),
        array("AF8751", "Madeira flutuante"),
        array("AF8F2C", "Alpino"),
        array("AF9F1C", "Por sorte"),
        array("AFA09E", "martini"),
        array("AFB1B8", "Bombaim"),
        array("AFBDD9", "Posto de pombo"),
        array("B04C6A", "Cadillac"),
        array("B05D54", "Matriz"),
        array("B05E81", "Tapeçaria"),
        array("B06608", "Mai Tai"),
        array("B09A95", "Del Río"),
        array("B0E0E6", "Pó azul"),
        array("B0E313", "Verme de Polegada"),
        array("B10000", "Vermelho brilhante"),
        array("B14A0B", "Vesúvio"),
        array("B1610B", "Pele de Abóbora"),
        array("B16D52", "Santa Fé"),
        array("B19461", "Teca"),
        array("B1E2C1", "Flor Franja"),
        array("B1F4E7", "Gelado"),
        array("B20931", "Shiraz"),
        array("B2A1EA", "Flor de Biloba"),
        array("B32D29", "Papoula alta"),
        array("B35213", "Laranja Flamejante"),
        array("B38007", "Toddy Quente"),
        array("B3AF95", "Cinza Taupe"),
        array("B3C110", "La Rioja"),
        array("B43332", "Bem Lido"),
        array("B44668", "Corar"),
        array("B4CFD3", "Névoa da Selva"),
        array("B57281", "Rosa turca"),
        array("B57EDC", "Lavanda"),
        array("B5A27F", "Mangusto"),
        array("B5B35C", "Verde oliva"),
        array("B5D2CE", "Corrente de jato"),
        array("B5ECDF", "Cruzeiro"),
        array("B6316C", "Hibisco"),
        array("B69D98", "palha"),
        array("B6B095", "Cinza Urze"),
        array("B6BAA4", "Águia"),
        array("B6D1EA", "Fuso"),
        array("B6D3BF", "Folha de goma"),
        array("B7410E", "Ferrugem"),
        array("B78E5C", "Águas turvas"),
        array("B7A214", "Saara"),
        array("B7A458", "Casca"),
        array("B7B1B1", "Nobel"),
        array("B7C3D0", "Mescla"),
        array("B7F0BE", "Madang"),
        array("B81104", "Vermelho Milano"),
        array("B87333", "Cobre"),
        array("B8B56A", "Verruma"),
        array("B8C1B1", "Primavera Verde"),
        array("B8C25D", "Salsão"),
        array("B8E0F9", "Velejar"),
        array("B94E48", "castanha"),
        array("B95140", "Crail"),
        array("B98D28", "calêndula"),
        array("B9C46A", "Salgueiro Selvagem"),
        array("B9C8AC", "Rainee"),
        array("BA0101", "Guarda Vermelho"),
        array("BA450C", "Spray de rocha"),
        array("BA6F1E", "Bourbon"),
        array("BA7F03", "Ouro Pirata"),
        array("BAB1A2", "Nômade"),
        array("BAC7C9", "Submarino"),
        array("BAEEF9", "Charlotte"),
        array("BB3385", "Violeta Vermelho Médio"),
        array("BB8983", "Brandy Rose"),
        array("BBD009", "Rio Grande"),
        array("BBD7C1", "Surfar"),
        array("BCC9C2", "Cinza em pó"),
        array("BD5E2E", "Toscana"),
        array("BD978E", "Areia movediça"),
        array("BDB1A8", "Seda"),
        array("BDB2A1", "Malta"),
        array("BDB3C7", "Châtela"),
        array("BDBBD7", "Cinza lavanda"),
        array("BDBDC6", "Cinza Francês"),
        array("BDC8B3", "Cinza de Argila"),
        array("BDC9CE", "Loblolly"),
        array("BDEDFD", "Passe Francês"),
        array("BEA6C3", "Tonalidade de Londres"),
        array("BEB5B7", "Cisne Rosa"),
        array("BEDE0D", "Fogo"),
        array("BF5500", "Rosa de Saron"),
        array("BFB8B0", "Maré"),
        array("BFBED8", "Névoa Azul"),
        array("BFC1C2", "Areia Prateada"),
        array("BFC921", "Torta de limão"),
        array("BFDBE2", "Zigurate"),
        array("BFFF00", "Lima"),
        array("C02B18", "Thunderbird"),
        array("C04737", "Mojo"),
        array("C08081", "Rosa Velha"),
        array("C0C0C0", "Prata"),
        array("C0D3B9", "Folha Pálida"),
        array("C0D8B6", "Pixie Verde"),
        array("C1440E", "Tia Maria"),
        array("C154C1", "Rosa fúcsia"),
        array("C1A004", "Buda Ouro"),
        array("C1B7A4", "Pele de Bisão"),
        array("C1BAB0", "Chá"),
        array("C1BECD", "Terno cinza"),
        array("C1D7B0", "brotar"),
        array("C1F07C", "Sulu"),
        array("C26B03", "Indoquina"),
        array("C2955D", "Corda"),
        array("C2BDB6", "Semente de algodão"),
        array("C2CAC4", "Pedra-pomes"),
        array("C2E8E5", "Gelo irregular"),
        array("C32148", "Rubor Marrom"),
        array("C3B091", "cáqui indiano"),
        array("C3BFC1", "Ardósia Pálida"),
        array("C3C3BD", "Níquel Cinza"),
        array("C3CDE6", "Cinza Pervinca"),
        array("C3D1D1", "Tiara"),
        array("C3DDF9", "Azul tropical"),
        array("C41E3A", "Cardeal"),
        array("C45655", "Fuzzy Wuzzy Brown"),
        array("C45719", "Peixe relógio"),
        array("C4C4BC", "Névoa Cinza"),
        array("C4D0B0", "Coentro"),
        array("C4F4EB", "Tulipa Menta"),
        array("C54B8C", "Amoreira"),
        array("C59922", "Pepita"),
        array("C5994B", "Tussock"),
        array("C5DBCA", "Névoa do mar"),
        array("C5E17A", "Amarelo verde"),
        array("C62D42", "Tijolo vermelho"),
        array("C6726B", "Contessa"),
        array("C69191", "Rosa Oriental"),
        array("C6A84B", "Roti"),
        array("C6C3B5", "Cinza"),
        array("C6C8BD", "Canguru"),
        array("C6E610", "Las Palmas"),
        array("C7031E", "Monza"),
        array("C71585", "Violeta vermelha"),
        array("C7BCA2", "Recife de corais"),
        array("C7C1FF", "Melrose"),
        array("C7C4BF", "Nuvem"),
        array("C7C9D5", "Fantasma"),
        array("C7CD90", "Clareira dos Pinheiros"),
        array("C7DDE5", "Botticelli"),
        array("C88A65", "Bronze antigo"),
        array("C8A2C8", "Lilás"),
        array("C8A528", "Hokey Pokey"),
        array("C8AABF", "Lírio"),
        array("C8B568", "Laser"),
        array("C8E3D7", "Edgewater"),
        array("C96323", "Flautista"),
        array("C99415", "pizza"),
        array("C9A0DC", "Glicínias Leves"),
        array("C9B29B", "Pó de Rodeio"),
        array("C9B35B", "Sundance"),
        array("C9B93B", "Conde Verde"),
        array("C9C0BB", "Ferrugem de Prata"),
        array("C9D9D2", "Concha"),
        array("C9FFA2", "Recife"),
        array("C9FFE5", "Azul Aero"),
        array("CA3435", "Mogno Flush"),
        array("CABB48", "Cúrcuma"),
        array("CADCD4", "Paris Branco"),
        array("CAE00D", "Limão azedo"),
        array("CAE6DA", "Cético"),
        array("CB8FA9", "Viola"),
        array("CBCAB6", "Cinza Nebuloso"),
        array("CBD3B0", "Névoa Verde"),
        array("CBDBD6", "Nebulosa"),
        array("CC3333", "Vermelho persa"),
        array("CC5500", "Laranja queimado"),
        array("CC7722", "Ocre"),
        array("CC8899", "Puce"),
        array("CCCAA8", "Cardo Verde"),
        array("CCCCFF", "Pervinca"),
        array("CCFF00", "Cal elétrica"),
        array("CD5700", "Tenn"),
        array("CD5C5C", "Rosa Castanha"),
        array("CD8429", "ponche de conhaque"),
        array("CDF4FF", "Onahaus"),
        array("CEB98F", "Sorrell Brown"),
        array("CEBABA", "Peru frio"),
        array("CEC291", "Yuma"),
        array("CEC7A7", "Chino"),
        array("CFA39D", "Eunry"),
        array("CFB53B", "Ouro Velho"),
        array("CFDCCF", "Tasman"),
        array("CFE5D2", "Crista de surf"),
        array("CFF9F3", "Beija Flor"),
        array("CFFAF4", "Escândalo"),
        array("D05F04", "Palco Vermelho"),
        array("D06DA1", "Hopbush"),
        array("D07D12", "Meteoro"),
        array("D0BEF8", "Perfume"),
        array("D0C0E5", "Prelúdio"),
        array("D0F0C0", "Chá Verde"),
        array("D18F1B", "Geebung"),
        array("D1BEA8", "Baunilha"),
        array("D1C6B4", "Âmbar Suave"),
        array("D1D2CA", "celeste"),
        array("D1D2DD", "Mischka"),
        array("D1E231", "Pera"),
        array("D2691E", "Canela Quente"),
        array("D27D46", "Siena crua"),
        array("D29EAA", "Carey Rosa"),
        array("D2B48C", "bronzeado"),
        array("D2DA97", "Deco"),
        array("D2F6DE", "Romance Azul"),
        array("D2F8B0", "Fofoca"),
        array("D3CBBA", "Sisal"),
        array("D3CDC5", "Redemoinho"),
        array("D47494", "Charme"),
        array("D4B6AF", "Concha de Amêijoas"),
        array("D4BF8D", "Canudo"),
        array("D4C4A8", "Akaroa"),
        array("D4CD16", "Flor de pássaro"),
        array("D4D7D9", "Ferro"),
        array("D4DFE2", "Gêiser"),
        array("D4E2FC", "Hawkes Blue"),
        array("D54600", "Granadeiro"),
        array("D591A4", "Pode, pode"),
        array("D59A6F", "Uísque"),
        array("D5D195", "Avelã de inverno"),
        array("D5F6E3", "Maçã Vovó"),
        array("D69188", "Meu Rosa"),
        array("D6C562", "Tacha"),
        array("D6CEF6", "Ancinho da Lua"),
        array("D6D6D1", "Pena Cinza"),
        array("D6FFDB", "Menta Nevado"),
        array("D7837F", "Rosa de Nova York"),
        array("D7C498", "Pavlova"),
        array("D7D0FF", "Névoa"),
        array("D84437", "Valência"),
        array("D87C63", "Japão"),
        array("D8BFD8", "Cardo"),
        array("D8C2D5", "Maverick"),
        array("D8FCFA", "Espuma"),
        array("D94972", "Cabaré"),
        array("D99376", "Areia ardente"),
        array("D9B99B", "Camafeu"),
        array("D9D6CF", "Lobo de madeira"),
        array("D9DCC1", "Tana"),
        array("D9E4F5", "Ligar Água"),
        array("D9F7FF", "Mabel"),
        array("DA3287", "Cerise"),
        array("DA5B38", "Ervilha Flamejante"),
        array("DA6304", "Bambu"),
        array("DA6A41", "Damasco Vermelho"),
        array("DA70D6", "Orquídea"),
        array("DA8A67", "Copperfield"),
        array("DAA520", "Grama Dourada"),
        array("DAECD6", "Zanah"),
        array("DAF4F0", "Iceberg"),
        array("DAFAFF", "Baía das Ostras"),
        array("DB5079", "Oxicoco"),
        array("DB9690", "Pequena orquídea"),
        array("DB995E", "Di Serria"),
        array("DBDBDB", "Alto"),
        array("DBFFF8", "Menta Fosco"),
        array("DC143C", "Carmesim"),
        array("DC4333", "Soco"),
        array("DCB20C", "Galliano"),
        array("DCB4BC", "Florescer"),
        array("DCD747", "Wattle"),
        array("DCD9D2", "Westar"),
        array("DCDDCC", "Névoa da Lua"),
        array("DCEDB4", "Alcaparra"),
        array("DCF0EA", "Cisnes para baixo"),
        array("DDD6D5", "Café Suíço"),
        array("DDF9F1", "Gelo Branco"),
        array("DE3163", "Vermelho Cerise"),
        array("DE6360", "romano"),
        array("DEA681", "Tumbleweed"),
        array("DEBA13", "Dicas de ouro"),
        array("DEC196", "conhaque"),
        array("DECBC6", "bolacha"),
        array("DED4A4", "Muda"),
        array("DED717", "Bérberis"),
        array("DEE5C0", "Verde Berilo"),
        array("DEF5FF", "Pattens Azul"),
        array("DF73FF", "Heliotrópio"),
        array("DFBE6F", "Apache"),
        array("DFCD6F", "Chenin"),
        array("DFCFDB", "Lola"),
        array("DFECDA", "Salgueiro"),
        array("DFFF00", "Amarelo Chartreuse"),
        array("E0B0FF", "Malva"),
        array("E0B646", "Anzac"),
        array("E0B974", "Colheita de Ouro"),
        array("E0C095", "Chita"),
        array("E0FFFF", "Bebê azul"),
        array("E16865", "Sunglo"),
        array("E1BC64", "Equador"),
        array("E1C0C8", "Flare Rosa"),
        array("E1E6D6", "Azul periglacial"),
        array("E1EAD4", "Seqüestrador"),
        array("E1F6E8", "Tara"),
        array("E25465", "Mandy"),
        array("E2725B", "Terracota"),
        array("E28913", "Sino Dourado"),
        array("E292C0", "Chocante"),
        array("E29418", "Dixie"),
        array("E29CD2", "Orquídea clara"),
        array("E2D8ED", "Rapé"),
        array("E2EBED", "Místico"),
        array("E2F3EC", "Maçã verde"),
        array("E30B5C", "Razzmatazz"),
        array("E32636", "Alizarina Carmesim"),
        array("E34234", "Cinábrio"),
        array("E3BEBE", "Caverna Rosa"),
        array("E3F5E1", "Hortelã-pimenta"),
        array("E3F988", "Mindaró"),
        array("E47698", "Blush Profundo"),
        array("E49B0F", "Gamboge"),
        array("E4C2D5", "Melanie"),
        array("E4CFDE", "Crepúsculo"),
        array("E4D1C0", "Osso"),
        array("E4D422", "Girassol"),
        array("E4D5B7", "Grão Marrom"),
        array("E4D69B", "Zumbi"),
        array("E4F6E7", "Frostee"),
        array("E4FFD1", "Nevasca"),
        array("E52B50", "Amaranto"),
        array("E5841B", "Entusiasmo"),
        array("E5CCC9", "Tempestade de areia"),
        array("E5D7BD", "Branco austero"),
        array("E5D8AF", "Hampton"),
        array("E5E0E1", "Bom dia"),
        array("E5E5E5", "Mercúrio"),
        array("E5F9F6", "Polar"),
        array("E64E03", "Trindade"),
        array("E6BE8A", "Areia Dourada"),
        array("E6BEA5", "Caxemira"),
        array("E6D7B9", "Duplo Espanhol Branco"),
        array("E6E4D4", "linho de cetim"),
        array("E6F2EA", "Harpa"),
        array("E6F8F3", "Verde desligado"),
        array("E6FFE9", "Dica de verde"),
        array("E6FFFF", "Tranquilo"),
        array("E77200", "Mango Tango"),
        array("E7730A", "Cristina"),
        array("E79F8C", "Tony Rosa"),
        array("E79FC4", "Kobi"),
        array("E7BCB4", "Névoa Rosa"),
        array("E7BF05", "Milho"),
        array("E7CD8C", "Massa"),
        array("E7ECE6", "Enfermeira Cinzenta"),
        array("E7F8FF", "Lírio branco"),
        array("E7FEFF", "Bolhas"),
        array("E89928", "Sarça de Fogo"),
        array("E8B9B3", "Shilo"),
        array("E8E0D5", "Pérola Bush"),
        array("E8EBE0", "Verde branco"),
        array("E8F1D4", "Branco cromado"),
        array("E8F2EB", "Gin"),
        array("E8F5F2", "Aqua Squeeze"),
        array("E96E00", "Clementina"),
        array("E97451", "Sienna queimado"),
        array("E97C07", "Ouro do Taiti"),
        array("E9CECD", "Rosa Ostra"),
        array("E9D75A", "Confete"),
        array("E9E3E3", "Ebb"),
        array("E9F8ED", "otomano"),
        array("E9FFFD", "Dia limpo"),
        array("EA88A8", "Carisma"),
        array("EAAE69", "Porsche"),
        array("EAB33B", "Tulipa"),
        array("EAC674", "Rob Roy"),
        array("EADAB8", "Ráfia"),
        array("EAE8D4", "Rocha Branca"),
        array("EAF6EE", "Panache"),
        array("EAF6FF", "Solidão"),
        array("EAF9F5", "Aqua Spring"),
        array("EAFFFE", "Orvalho"),
        array("EB9373", "Damasco"),
        array("EBC2AF", "Zinnwaldita"),
        array("ECA927", "Combustível Amarelo"),
        array("ECC54E", "Ronchi"),
        array("ECC7EE", "Lilás francês"),
        array("ECCDB9", "Na medida"),
        array("ECE090", "Arroz selvagem"),
        array("ECEBBD", "Outono Verde"),
        array("ECEBCE", "Especial Aths"),
        array("ECF245", "nave estelar"),
        array("ED0A3F", "Laço vermelho"),
        array("ED7A1C", "Tango"),
        array("ED9121", "Cenoura Laranja"),
        array("ED989E", "Rosa Mar"),
        array("EDB381", "Tacao"),
        array("EDC9AF", "Areia do deserto"),
        array("EDCDAB", "Pancho"),
        array("EDDCB1", "Camurça"),
        array("EDEA99", "Prímula"),
        array("EDF5DD", "geada"),
        array("EDF5F5", "Aqua Haze"),
        array("EDF6FF", "Zumthor"),
        array("EDF9F1", "Narvik"),
        array("EDFC84", "Madressilva"),
        array("EE82EE", "Lavanda Magenta"),
        array("EEC1BE", "Beleza Bush"),
        array("EED794", "Giz"),
        array("EED9C4", "Amêndoa"),
        array("EEDC82", "Linho"),
        array("EEDEDA", "Bizarro"),
        array("EEE3AD", "Branco Colonial Duplo"),
        array("EEEEE8", "Cararra"),
        array("EEEF78", "Manz"),
        array("EEF0C8", "Areias de Tahuna"),
        array("EEF0F3", "Atenas Cinza"),
        array("EEF3C3", "Presa"),
        array("EEF4DE", "Mocassim"),
        array("EEF6F7", "Catskill Branco"),
        array("EEFDFF", "Azul Crepúsculo"),
        array("EEFF9A", "Jonquil"),
        array("EEFFE2", "Flor de Arroz"),
        array("EF863F", "Jafa"),
        array("EFEFEF", "Galeria"),
        array("EFF2F3", "Porcelana"),
        array("F091A9", "Mauvelous"),
        array("F0D52D", "Sonho Dourado"),
        array("F0DB7D", "Areia dourada"),
        array("F0DC82", "Aficionado"),
        array("F0E2EC", "Prim"),
        array("F0E68C", "cáqui"),
        array("F0EEFD", "Selago"),
        array("F0EEFF", "Titã Branco"),
        array("F0F8FF", "Alice Azul"),
        array("F0FCEA", "Feta"),
        array("F18200", "Gold Drop"),
        array("F19BAB", "Wewak"),
        array("F1E788", "Areia do Saara"),
        array("F1E9D2", "Pergaminho"),
        array("F1E9FF", "Giz Azul"),
        array("F1EEC1", "Mint Julep"),
        array("F1F1F1", "Concha do mar"),
        array("F1F7F2", "Salina"),
        array("F1FFAD", "Maré"),
        array("F1FFC8", "Chiffon"),
        array("F2552A", "Flamingo"),
        array("F28500", "tangerina"),
        array("F2C3B2", "Mandys Rosa"),
        array("F2F2F2", "Concreto"),
        array("F2FAFA", "Aperto Preto"),
        array("F34723", "Romã"),
        array("F3AD16", "Botão de ouro"),
        array("F3D69D", "Nova Orleans"),
        array("F3D9DF", "Sorvete de baunilha"),
        array("F3E7BB", "Sidecar"),
        array("F3E9E5", "Rosa Amanhecer"),
        array("F3EDCF", "Campo de trigo"),
        array("F3FB62", "Canário"),
        array("F3FBD4", "Orinoco"),
        array("F3FFD8", "Carla"),
        array("F400A1", "Cerise de Hollywood"),
        array("F4A460", "marrom arenoso"),
        array("F4C430", "Açafrão"),
        array("F4D81C", "Limão Maduro"),
        array("F4EBD3", "Janna"),
        array("F4F2EE", "Pampas"),
        array("F4F4F4", "Areia Selvagem"),
        array("F4F8FF", "Zircão"),
        array("F57584", "Brincadeira"),
        array("F5C85C", "Lata de creme"),
        array("F5C999", "Manhattan"),
        array("F5D5A0", "Milho"),
        array("F5DEB3", "Trigo"),
        array("F5E7A2", "Sandwisp"),
        array("F5E7E2", "Pot Pourri"),
        array("F5E9D3", "Branco Albescente"),
        array("F5EDEF", "Pêssego Macio"),
        array("F5F3E5", "Branco cru"),
        array("F5F5DC", "Bege"),
        array("F5FB3D", "Fizz Dourado"),
        array("F5FFBE", "Casa da Moeda Australiana"),
        array("F64A8A", "Rosa Francesa"),
        array("F653A6", "Rosa brilhante"),
        array("F6A4C9", "Ilusão"),
        array("F6F0E6", "Merino"),
        array("F6F7F7", "Neblina Negra"),
        array("F6FFDC", "Sol da Primavera"),
        array("F7468A", "Vermelho Violeta"),
        array("F77703", "Fogo chileno"),
        array("F77FBE", "Rosa persa"),
        array("F7B668", "Rajá"),
        array("F7C8DA", "Azaléia"),
        array("F7DBE6", "Nós espiamos"),
        array("F7F2E1", "Quarto Espanhol Branco"),
        array("F7F5FA", "Sussurrar"),
        array("F7FAF7", "Deriva de neve"),
        array("F8B853", "Casablanca"),
        array("F8C3DF", "chantilly"),
        array("F8D9E9", "Querubim"),
        array("F8DB9D", "Marzipan"),
        array("F8DD5C", "Energia Amarelo"),
        array("F8E4BF", "Givry"),
        array("F8F0E8", "linho branco"),
        array("F8F4FF", "Magnólia"),
        array("F8F6F1", "Madeira da Primavera"),
        array("F8F7DC", "Creme de coco"),
        array("F8F7FC", "Lilás Branco"),
        array("F8F8F7", "Tempestade no Deserto"),
        array("F8F99C", "Texas"),
        array("F8FACD", "Campo de milho"),
        array("F8FDD3", "Mimosa"),
        array("F95A61", "Cravo"),
        array("F9BF58", "Manga Açafrão"),
        array("F9E0ED", "Carrossel Rosa"),
        array("F9E4BC", "Creme de leite"),
        array("F9E663", "Portica"),
        array("F9EAF3", "Amor"),
        array("F9F8E4", "Rum Swizzle"),
        array("F9FF8B", "Dolly"),
        array("F9FFF6", "Cana de açúcar"),
        array("FA7814", "Êxtase"),
        array("FA9D5A", "Couro bronzeado"),
        array("FAD3A2", "Corveta"),
        array("FADFAD", "Amarelo Pêssego"),
        array("FAE600", "Turbo"),
        array("FAEAB9", "Astra"),
        array("FAECCC", "champanhe"),
        array("FAF0E6", "Linho"),
        array("FAF3F0", "Fantasia"),
        array("FAF7D6", "Citrino Branco"),
        array("FAFAFA", "Alabastro"),
        array("FAFDE4", "Dica de amarelo"),
        array("FAFFA4", "Milão"),
        array("FB607F", "Brink Pink"),
        array("FB8989", "Geraldine"),
        array("FBA0E3", "Rosa Lavanda"),
        array("FBA129", "Espinheiro Marinho"),
        array("FBAC13", "Sol"),
        array("FBAED2", "Rosa Lavanda"),
        array("FBB2A3", "botão de rosa"),
        array("FBBEDA", "cupido"),
        array("FBCCE7", "Rosa Clássica"),
        array("FBCEB1", "Damasco Pêssego"),
        array("FBE7B2", "Bananamania"),
        array("FBE870", "Amarelo calêndula"),
        array("FBE96C", "Festival"),
        array("FBEA8C", "Milho doce"),
        array("FBEC5D", "Milho doce"),
        array("FBF9F9", "Dica de vermelho"),
        array("FBFFBA", "Shalimar"),
        array("FC0FC0", "Rosa choque"),
        array("FC80A5", "Faça cócegas em mim rosa"),
        array("FC9C1D", "Papoila"),
        array("FCC01E", "Amarelo Relâmpago"),
        array("FCD667", "Goldenrod"),
        array("FCD917", "Luz de velas"),
        array("FCDA98", "Cherokee"),
        array("FCF4D0", "Dupla Pérola Lusta"),
        array("FCF4DC", "Pérola Lusta"),
        array("FCF8F7", "Vista Branca"),
        array("FCFBF3", "Bianca"),
        array("FCFEDA", "Brilho da Lua"),
        array("FCFFE7", "Marfim da China"),
        array("FCFFF9", "Cerâmica"),
        array("FD0E35", "Tocha vermelha"),
        array("FD5B78", "Melancia Selvagem"),
        array("FD7B33", "Crusta"),
        array("FD7C07", "Sorbus"),
        array("FD9FA2", "Rosa doce"),
        array("FDD5B1", "Damasco Claro"),
        array("FDD7E4", "Rosa Porco"),
        array("FDE1DC", "Cinderela"),
        array("FDE295", "Brilho Dourado"),
        array("FDE910", "Limão"),
        array("FDF5E6", "Renda Velha"),
        array("FDF6D3", "Branco meio colonial"),
        array("FDF7AD", "Drover"),
        array("FDFEB8", "Pale Prim"),
        array("FDFFD5", "Cumulus"),
        array("FE28A2", "Rosa Persa"),
        array("FE4C40", "Laranja Pôr do Sol"),
        array("FE6F5E", "Agridoce"),
        array("FE9D04", "Califórnia"),
        array("FEA904", "Mar Amarelo"),
        array("FEBAAD", "Melão"),
        array("FED33C", "Sol brilhante"),
        array("FED85D", "Dente-de-leão"),
        array("FEDB8D", "Salomie"),
        array("FEE5AC", "Mel do Cabo"),
        array("FEEBF3", "Remy"),
        array("FEEFCE", "Oásis"),
        array("FEF0EC", "Dama de honra"),
        array("FEF2C7", "Cera de abelha"),
        array("FEF3D8", "Branco descolorante"),
        array("FEF4CC", "Pipi"),
        array("FEF4DB", "Meio espanhol branco"),
        array("FEF4F8", "Cor-de-rosa"),
        array("FEF5F1", "Rosa provincial"),
        array("FEF7DE", "Meio Holandês Branco"),
        array("FEF8E2", "Solitário"),
        array("FEF8FF", "Ponteiro Branco"),
        array("FEF9E3", "Desligado Amarelo"),
        array("FEFCED", "Laranja Branco"),
        array("FF0000", "Vermelho"),
        array("FF007F", "Rosa"),
        array("FF00CC", "Pizzazz Roxo"),
        array("FF00FF", "Magenta / Fúcsia"),
        array("FF2400", "Escarlate"),
        array("FF3399", "Morango Selvagem"),
        array("FF33CC", "Deslumbrar Deslumbrar Rosa"),
        array("FF355E", "Vermelho Radical"),
        array("FF3F34", "Laranja vermelha"),
        array("FF4040", "Vermelho coral"),
        array("FF4D00", "Vermelhão"),
        array("FF4F00", "Laranja Internacional"),
        array("FF6037", "Laranja ultrajante"),
        array("FF6600", "Laranja Flamejante"),
        array("FF66FF", "Flamingo Rosa"),
        array("FF681F", "Laranja"),
        array("FF69B4", "Rosa quente"),
        array("FF6B53", "Caqui"),
        array("FF6FFF", "Cor-de-rosa"),
        array("FF7034", "Laranja Ardente"),
        array("FF7518", "Abóbora"),
        array("FF7D07", "Flamenco"),
        array("FF7F00", "Laranja Fluído"),
        array("FF7F50", "Coral"),
        array("FF8C69", "Salmão"),
        array("FF9000", "Pizazz"),
        array("FF910F", "lado oeste"),
        array("FF91A4", "Salmão Rosa"),
        array("FF9933", "Cenoura Neon"),
        array("FF9966", "Tangerina Atômica"),
        array("FF9980", "Tangerina viva"),
        array("FF9E2C", "Guarda-sol"),
        array("FFA000", "Casca de laranja"),
        array("FFA194", "Monalisa"),
        array("FFA500", "Web Laranja"),
        array("FFA6C9", "Cravo Rosa"),
        array("FFAB81", "Acerte Rosa"),
        array("FFAE42", "Amarelo alaranjado"),
        array("FFB0AC", "Centáurea Lilás"),
        array("FFB1B3", "Pôr do sol"),
        array("FFB31F", "Meu pecado"),
        array("FFB555", "Rosa do Texas"),
        array("FFB7D5", "Algodão doce"),
        array("FFB97B", "Macarrão com queijo"),
        array("FFBA00", "Amarelo seletivo"),
        array("FFBD5F", "Koromiko"),
        array("FFBF00", "Âmbar"),
        array("FFC0A8", "Flor de cera"),
        array("FFC0CB", "Rosa"),
        array("FFC3C0", "Seu rosa"),
        array("FFC901", "Super Nova"),
        array("FFCBA4", "Carne"),
        array("FFCC33", "Sunglow"),
        array("FFCC5C", "Tainoi Dourado"),
        array("FFCC99", "Pêssego Laranja"),
        array("FFCD8C", "Chardonnay"),
        array("FFD1DC", "Rosa pastel"),
        array("FFD2B7", "Romântico"),
        array("FFD38C", "Grandis"),
        array("FFD700", "Ouro"),
        array("FFD800", "ônibus escolar amarelo"),
        array("FFD8D9", "Cosmos"),
        array("FFDB58", "Mostarda"),
        array("FFDCD6", "Schnapps de pêssego"),
        array("FFDDAF", "Caramelo"),
        array("FFDDCD", "Tufo de arbusto"),
        array("FFDDCF", "Watusi"),
        array("FFDDF4", "Renda Rosa"),
        array("FFDEAD", "Branco Navajo"),
        array("FFDEB3", "Frangipani"),
        array("FFE1DF", "Pippin"),
        array("FFE1F2", "Rosa pálida"),
        array("FFE2C5", "Negroni"),
        array("FFE5A0", "Creme Brulée"),
        array("FFE5B4", "Pêssego"),
        array("FFE6C7", "Tequila"),
        array("FFE772", "Kournikova"),
        array("FFEAC8", "Praia"),
        array("FFEAD4", "Karry"),
        array("FFEC13", "Vassoura"),
        array("FFEDBC", "Branco colonial"),
        array("FFEED8", "Derby"),
        array("FFEFA1", "Vis Vis"),
        array("FFEFC1", "Clara de ovo"),
        array("FFEFD5", "Chicote de papaia"),
        array("FFEFEC", "Rosa claro"),
        array("FFF0DB", "Creme de Pêssego"),
        array("FFF0F5", "blush lavanda"),
        array("FFF14F", "Tojo"),
        array("FFF1B5", "Soro de leite coalhado"),
        array("FFF1D8", "Dama Rosa"),
        array("FFF1EE", "Não me esqueça"),
        array("FFF1F9", "Tutu"),
        array("FFF39D", "Picasso"),
        array("FFF3F1", "Chardon"),
        array("FFF46E", "Margarida de Paris"),
        array("FFF4CE", "Cevada Branca"),
        array("FFF4DD", "Ovo Azedo"),
        array("FFF4E0", "Sazerac"),
        array("FFF4E8", "Serenata"),
        array("FFF4F3", "Chablis"),
        array("FFF5EE", "Concha Pêssego"),
        array("FFF5F3", "Sauvignon"),
        array("FFF6D4", "Ponche de Leite"),
        array("FFF6DF", "Varden"),
        array("FFF6F5", "Rosa Branca"),
        array("FFF8D1", "Baixa Branca"),
        array("FFF9E2", "Gin Fizz"),
        array("FFF9E6", "Amanhecer"),
        array("FFFACD", "Chiffon de Limão"),
        array("FFFAF4", "Charneca nupcial"),
        array("FFFBDC", "Névoa Escocesa"),
        array("FFFBF9", "Pedra-sabão"),
        array("FFFC99", "Bruxa da Bruxa"),
        array("FFFCEA", "Branco amanteigado"),
        array("FFFCEE", "Tempero da Ilha"),
        array("FFFDD0", "Creme"),
        array("FFFDE6", "Charneca chilena"),
        array("FFFDE8", "Travertino"),
        array("FFFDF3", "Orquídea Branca"),
        array("FFFDF4", "Quarto Pérola Lusta"),
        array("FFFEE1", "Metade e metade"),
        array("FFFEEC", "Branco de Damasco"),
        array("FFFEF0", "Bolo de arroz"),
        array("FFFEF6", "Preto branco"),
        array("FFFEFD", "Romance"),
        array("FFFF00", "Amarelo"),
        array("FFFF66", "Laser Limão"),
        array("FFFF99", "Canário pálido"),
        array("FFFFB4", "Portafino"),
        array("FFFFF0", "Marfim"),
        array("FFFFFF", "Branco")
    );
}